name: Test

on:
  pull_request:
    types: [ opened, synchronize, reopened]
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Setup test env
        run: cp ./example.env ./.env

      - name: Run tests
        run: make test
