name: Test

on:
  pull_request:
    types: [ opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: go test -race ./...

      - name: Run Fuzzy tests
        run: go test -fuzztime 5s -fuzz FuzzPostGreeting
